- icon: people-carry
  title: Indigenous Leadership
  content: We will operate on the principle that community ownership and active participation are more important than
    speed and efficiency.
- icon: globe-africa
  title: Local Cultures
  content: We recognize that all cultures and traditions have value, and we support cultures and traditions which serve
    the good of all parties.
- icon: balance-scale
  title: Honesty and Transparency
  content: We operate with honesty and transparency. We ensure our projects comply with the laws and regulations of the
    host countries.
